name: Generate News JSON

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate_news_json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          
      - name: Install dependencies
        run: npm install rss-parser


      - name: Fetch RSS feeds and generate JSON
        run: |
          node <<EOF
          const Parser = require('rss-parser');
          const fs = require('fs');

          // Define the list of RSS feed URLs
          const rssFeeds = [
            'https://cfo.economictimes.indiatimes.com/rss',
            'https://anotherexample.com/rss'
            // Add more RSS feed URLs as needed
          ];

          // Initialize RSS parser
          const parser = new Parser();

          // Function to fetch and parse RSS feeds
          async function fetchFeeds() {
            const allNews = [];

            // Fetch each RSS feed
            for (const feedUrl of rssFeeds) {
              try {
                const feed = await parser.parseURL(feedUrl);
                // Extract news items from the feed
                const newsItems = feed.items.map(item => ({
                  title: item.title,
                  link: item.link,
                  date: item.pubDate
                }));
                // Add news items to the list
                allNews.push(...newsItems);
              } catch (error) {
                console.error('Error fetching RSS feed:', feedUrl, error);
              }
            }

            // Write news items to JSON file
            fs.writeFileSync('news.json', JSON.stringify(allNews, null, 2));
          }

          fetchFeeds();
          EOF
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news.json
          git commit -m "Update news.json [skip ci]"
          git push
